### PR TITLE
Fixing the ruby-mail package dependency for Debian

### PR DESCRIPTION
**Pull request by liamjbennett**

### CODE REVIEW

**Comment by solarkennedy** [comment]
We use Ubuntu, so maybe we are just behind on packages.

I don't really like all this pinning inside, it makes it difficult for other people to use (hence the PR)

Instead can you make it a class param and just default to latest, and then on our side we can pin back to whatever version we need? (via hiera)

**Comment by fessyfoo** [comment]
where does the rubygem-mail package  come from?  AFAICT  it wasn't in any release of ubuntu.  

http://packages.ubuntu.com/search?suite=trusty&section=all&arch=any&keywords=rubygem-mail&searchon=names

does Yelp have it's own deb packaging of ruby gems?

**Comment by solarkennedy** [comment]
Yea, I think I may have just `fpm -s gem -t deb mail`. 

Looks like the tests are failing, but probably from a different reason. Can you merge master to make sure it is running up against the latest fixtures?

**Comment by fessyfoo** [comment]
master currently fails to pass tests.  the latest monitoring_check requires a newer version of sensu_check  which is pinned to an older version in the .fixtures file.

**Comment by liamjbennett** [comment]
Closing in favor of #60

**Pull request closed without merging**
