### PR TITLE
Allow removal of Dashboard link by setting variable to nil

### PR DESCRIPTION
**Pull request by davent**

### CODE REVIEW

**Review by bobtfish — CHANGES_REQUESTED** [review]
Why not just remove this?

**Comment by davent** [comment]
To allow for the option of easily bringing it back without having to do a complete code revert.

**Comment by bobtfish** [comment]
> To allow for the option of easily bringing it back without having to do a complete code revert.

I don't buy it :) Simpler just to remove the functionality that we have no plans to ever use again.

**Comment by davent** [comment]
Fine, it's gone.

**Review by bobtfish — APPROVED** [review]

**Review by timmow — APPROVED** [review]

**Pull request merged**
